### ISSUE TITLE
Call the self-attention, and throw the exception about tf.layer.dense.

### ISSUE THREAD

**Issue by huiMM** [st9007a/ChineseQABot#8]
excepiton is :
> File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py", line 1005, in build     raise ValueError('The last dimension of the inputs to `Dense` '
> ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

the code is:
`atten = self_attention(fully1,training=True)`
definition
```
def self_attention(inputs, training, *args, **kwargs):
   with tf.variable_scope('self_attention'):
        q = tf.layers.dense(inputs=inputs, units= 512, activation=None, name="query")
        k = tf.layers.dense(inputs=inputs, units= 512 activation=None, name="key")
        v = tf.layers.dense(inputs=inputs, units= 512, activation=None, name="value")

        logits = tf.matmul(q, k, transpose_b=True)
```

**Comment by st9007a** [comment]
Well, to debug easily, could you provide the full code and the full error message ?
